<a href="https://colab.research.google.com/github/iankurbhatt/AI-Data-Analyst-Agent/blob/main/database_setup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import sqllite in python

In [1]:
import sqlite3

Create the database file

In [2]:
connection=sqlite3.connect("business.db")

Create a cursor

In [3]:
cursor=connection.cursor()

Verify the database was created

In [4]:
import os
os.listdir()

['.config', 'business.db', 'sample_data']

Create customers table

In [5]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS customers (
customer_id INTEGER PRIMARY KEY,
customer_name TEXT,
city TEXT
)
""")

Create Products table

In [6]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS products (
product_id INTEGER PRIMARY KEY,
product_name TEXT,
category TEXT,
price REAL
)
""")

Create Orders table

In [7]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS orders (
order_id INTEGER PRIMARY KEY,
customer_id INTEGER,
product_id INTEGER,
quantity INTEGER,
order_date TEXT
)
""")

Save changes to database

In [8]:
connection.commit()

Check all tables were created

In [9]:
cursor.execute("""
Select name from sqlite_master
where type='table'
""")
print(cursor.fetchall())

[('customers',), ('products',), ('orders',)]

Close the connection

In [10]:
connection.close()

Restart

In [11]:
import sqlite3

connection=sqlite3.connect("business.db")
cursor=connection.cursor()

Insert customers data

In [12]:
customers=[
    (1, "Ankur", "Gurugram"),
    (2, "Rahul", "Delhi"),
    (3, "Priya", "Mumbai"),
    (4, "Neha", "Bengaluru"),
    (5, "Amit", "Pune")
]
cursor.executemany("""
INSERT into customers VALUES (?,?,?)
""",customers)

Insert products data

In [13]:
products=[
    (101, "Laptop", "Electronics", 70000),
    (102, "Mobile Phone", "Electronics", 30000),
    (103, "Headphones", "Accessories", 2000),
    (104, "Office Chair", "Furniture", 8000),
    (105, "Water Bottle", "Lifestyle", 500)
]
cursor.executemany("""
INSERT into products VALUES (?,?,?,?)
""",products)

Insert orders data

In [14]:
orders=[
    (1001, 1, 101, 1, "2026-06-01"),
    (1002, 2, 102, 2, "2026-06-03"),
    (1003, 3, 103, 3, "2026-06-05"),
    (1004, 1, 104, 1, "2026-06-10"),
    (1005, 5, 101, 1, "2026-06-15"),
    (1006, 4, 105, 5, "2026-06-20")
]
cursor.executemany("""
INSERT into orders VALUES (?,?,?,?,?)
""",orders)

Save the data

In [15]:
connection.commit()

Verify customers data

In [16]:
cursor.execute("""
SELECT * from customers
""")
print(cursor.fetchall())

[(1, 'Ankur', 'Gurugram'), (2, 'Rahul', 'Delhi'), (3, 'Priya', 'Mumbai'), (4, 'Neha', 'Bengaluru'), (5, 'Amit', 'Pune')]

Verify products

In [17]:
cursor.execute("""
SELECT * from products
""")
print(cursor.fetchall())

[(101, 'Laptop', 'Electronics', 70000.0), (102, 'Mobile Phone', 'Electronics', 30000.0), (103, 'Headphones', 'Accessories', 2000.0), (104, 'Office Chair', 'Furniture', 8000.0), (105, 'Water Bottle', 'Lifestyle', 500.0)]

Verify orders

In [18]:
cursor.execute("""
SELECT * from orders
""")
print(cursor.fetchall())

[(1001, 1, 101, 1, '2026-06-01'), (1002, 2, 102, 2, '2026-06-03'), (1003, 3, 103, 3, '2026-06-05'), (1004, 1, 104, 1, '2026-06-10'), (1005, 5, 101, 1, '2026-06-15'), (1006, 4, 105, 5, '2026-06-20')]

Close connection

In [19]:
connection.close()

Connect to database

In [20]:
import sqlite3
connection=sqlite3.connect("business.db")
cursor=connection.cursor()

View All Orders
Business Question:

"Show me all orders"

In [21]:
cursor.execute("""
Select * from orders
""")
print(cursor.fetchall())

[(1001, 1, 101, 1, '2026-06-01'), (1002, 2, 102, 2, '2026-06-03'), (1003, 3, 103, 3, '2026-06-05'), (1004, 1, 104, 1, '2026-06-10'), (1005, 5, 101, 1, '2026-06-15'), (1006, 4, 105, 5, '2026-06-20')]

Select Specific Columns
Business Question:

"Show me customer names and their cities"

In [22]:
cursor.execute("""
SELECT customer_name, city
FROM customers
""")

print(cursor.fetchall())

[('Ankur', 'Gurugram'), ('Rahul', 'Delhi'), ('Priya', 'Mumbai'), ('Neha', 'Bengaluru'), ('Amit', 'Pune')]

Filter Data with WHERE

A company may ask:

"Show customers from Delhi"

In [23]:
cursor.execute("""
SELECT *
FROM customers
WHERE city = 'Delhi'
""")

print(cursor.fetchall())

[(2, 'Rahul', 'Delhi')]

Sort Data with ORDER BY

Business Question:

"Show products from highest price to lowest"

In [24]:
cursor.execute("""
SELECT *
FROM products
ORDER BY price DESC
""")

print(cursor.fetchall())

[(101, 'Laptop', 'Electronics', 70000.0), (102, 'Mobile Phone', 'Electronics', 30000.0), (104, 'Office Chair', 'Furniture', 8000.0), (103, 'Headphones', 'Accessories', 2000.0), (105, 'Water Bottle', 'Lifestyle', 500.0)]

Count Records with COUNT

Business Question:

"How many customers do we have?"

In [25]:
cursor.execute("""
SELECT COUNT(*)
FROM customers
""")

print(cursor.fetchall())

[(5,)]

Calculate Total Quantity Sold

Business Question:

"How many products have we sold?"

In [26]:
cursor.execute("""
SELECT SUM(quantity)
FROM orders
""")

print(cursor.fetchall())

[(13,)]

Customer Purchase Report

In [27]:
cursor.execute("""
SELECT
    customers.customer_name,
    products.product_name,
    orders.quantity,
    orders.order_date
FROM orders

JOIN customers
ON orders.customer_id = customers.customer_id

JOIN products
ON orders.product_id = products.product_id
""")

results = cursor.fetchall()

for row in results:
    print(row)

('Ankur', 'Laptop', 1, '2026-06-01')
('Rahul', 'Mobile Phone', 2, '2026-06-03')
('Priya', 'Headphones', 3, '2026-06-05')
('Ankur', 'Office Chair', 1, '2026-06-10')
('Amit', 'Laptop', 1, '2026-06-15')
('Neha', 'Water Bottle', 5, '2026-06-20')

Find Top Selling Products

Now a real business analysis.

Question:

"Which products sold the most units?"

In [28]:
cursor.execute("""
SELECT
    products.product_name,
    SUM(orders.quantity) AS total_units_sold

FROM orders

JOIN products
ON orders.product_id = products.product_id

GROUP BY products.product_name

ORDER BY total_units_sold DESC
""")

print(cursor.fetchall())

[('Water Bottle', 5), ('Headphones', 3), ('Mobile Phone', 2), ('Laptop', 2), ('Office Chair', 1)]

Close Database Connection

In [29]:
connection.close()

Install pandas

In [30]:
import pandas as pd

Connect to database

In [31]:
connection=sqlite3.connect("business.db")

Load customer table into pandas

In [32]:
query = "SELECT * from customers"
customers_df = pd.read_sql(query, connection)
customers_df

   customer_id customer_name       city
0            1         Ankur   Gurugram
1            2         Rahul      Delhi
2            3         Priya     Mumbai
3            4          Neha  Bengaluru
4            5          Amit       Pune

Load products table

In [33]:
products_df = pd.read_sql("SELECT * from products",connection)
products_df

   product_id  product_name     category    price
0         101        Laptop  Electronics  70000.0
1         102  Mobile Phone  Electronics  30000.0
2         103    Headphones  Accessories   2000.0
3         104  Office Chair    Furniture   8000.0
4         105  Water Bottle    Lifestyle    500.0

Basic analysis(Most expensive product)

In [34]:
products_df.sort_values(by="price",ascending=False)

   product_id  product_name     category    price
0         101        Laptop  Electronics  70000.0
1         102  Mobile Phone  Electronics  30000.0
3         104  Office Chair    Furniture   8000.0
2         103    Headphones  Accessories   2000.0
4         105  Water Bottle    Lifestyle    500.0

Filter electronic products

In [35]:
products_df[products_df["category"] == "Electronics"]

   product_id  product_name     category    price
0         101        Laptop  Electronics  70000.0
1         102  Mobile Phone  Electronics  30000.0

Load a join query into pandas

In [37]:
sales_df = pd.read_sql("""
SELECT customers.customer_name,
products.product_name,
products.price,
orders.quantity,
orders.order_date
FROM orders
JOIN customers
ON orders.customer_id = customers.customer_id
JOIN products
ON orders.product_id = products.product_id
""",connection)
sales_df

  customer_name  product_name    price  quantity  order_date
0         Ankur        Laptop  70000.0         1  2026-06-01
1         Rahul  Mobile Phone  30000.0         2  2026-06-03
2         Priya    Headphones   2000.0         3  2026-06-05
3         Ankur  Office Chair   8000.0         1  2026-06-10
4          Amit        Laptop  70000.0         1  2026-06-15
5          Neha  Water Bottle    500.0         5  2026-06-20

Create revenue column

In [38]:
sales_df["revenue"] = (sales_df["price"] * sales_df["quantity"])
sales_df

  customer_name  product_name    price  quantity  order_date  revenue
0         Ankur        Laptop  70000.0         1  2026-06-01  70000.0
1         Rahul  Mobile Phone  30000.0         2  2026-06-03  60000.0
2         Priya    Headphones   2000.0         3  2026-06-05   6000.0
3         Ankur  Office Chair   8000.0         1  2026-06-10   8000.0
4          Amit        Laptop  70000.0         1  2026-06-15  70000.0
5          Neha  Water Bottle    500.0         5  2026-06-20   2500.0

Calculate total revenue

In [39]:
sales_df["revenue"].sum()

np.float64(216500.0)

Find top revenue products

In [41]:
sales_df.groupby("product_name")["revenue"].sum().sort_values(ascending=False)

product_name
Laptop          140000.0
Mobile Phone     60000.0
Office Chair      8000.0
Headphones        6000.0
Water Bottle      2500.0
Name: revenue, dtype: float64

Close connection

In [42]:
connection.close()